spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/waitque
    username: waitque_api
    password: zDsCDGN96h7J
    jpa:
      hibernate:
        ddl-auto: validate # or validate / create-drop (dev only)
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          default_schema: waitque
    flyway:
      enabled: true
      locations: classpath:db/migration
      schemas: waitque
logging:
  level:
    org.springframework.security: INFO