spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/waitque?currentSchema=waitque
    username: waitque_api
    password: ${WAITQUE_DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: validate # or validate / create-drop (dev only)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: waitque

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: waitque
    default-schema: waitque

logging:
  level:
    org.springframework.security: INFO